# Generated by Django 5.2.6 on 2025-09-23 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('topics', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=20)),
                ('payload', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='apps.course')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('mcq/single', 'MCQ Single'), ('mcq/multi', 'MCQ Multi'), ('short', 'Short'), ('numeric', 'Numeric'), ('ordering', 'Ordering'), ('matching', 'Matching')], max_length=32)),
                ('stem', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('answer', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('difficulty', models.IntegerField()),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='apps.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('started', 'Started'), ('finished', 'Finished'), ('graded', 'Graded')], default='started', max_length=10)),
                ('items', models.ManyToManyField(to='apps.item')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('breakdown', models.JSONField(default=list)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='apps.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('payload', models.JSONField(default=list)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='apps.item')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='apps.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizBlueprint',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rules', models.JSONField(default=dict)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blueprints', to='apps.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='blueprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='apps.quizblueprint'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='apps.user'),
        ),
    ]
