# Generated by Django 5.2.6 on 2025-10-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='grading_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='answer',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='max_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GradingRule',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('mcq/single', 'MCQ Single'), ('mcq/multi', 'MCQ Multi'), ('short', 'Short'), ('numeric', 'Numeric'), ('ordering', 'Ordering'), ('matching', 'Matching')], max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('scoring_function', models.CharField(max_length=50)),
                ('weight', models.FloatField(default=1.0)),
                ('parameters', models.JSONField(default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['item_type'], name='apps_gradin_item_ty_09c995_idx')],
            },
        ),
    ]
